// <auto-generated />
using System;
using DevalCopilot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevalCopilot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DevalCopilotDbContext))]
    [Migration("20260921142853_AddAgentAssignmentFacts")]
    partial class AddAgentAssignmentFacts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("DevalCopilot.Domain.Features.EnvironmentReadiness.HostCapabilitySnapshot", b =>
                {
                    b.Property<string>("Capability")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EvidenceObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LaunchKind")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("NextProbeDueAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservedVersion")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ProbeDispatchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedExecutablePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedScriptPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Capability");

                    b.ToTable("host_capability_snapshots", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.CheckpointReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckpointFingerprintSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("CheckpointNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GitCheckpointId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GitWorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("RecordedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GitCheckpointId");

                    b.HasIndex("GitWorkspaceId");

                    b.HasIndex("ProjectId", "RecordedAtUtcTicks", "Id");

                    b.ToTable("checkpoint_reviews", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.CheckpointReviewEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CheckpointReviewId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VerificationCommandId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationExecutionCheckpointFingerprintSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("VerificationExecutionExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VerificationExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("VerificationExecutionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VerificationExecutionOutcome")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationExecutionStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VerificationCommandId");

                    b.HasIndex("VerificationExecutionId");

                    b.HasIndex("CheckpointReviewId", "VerificationCommandId")
                        .IsUnique();

                    b.HasIndex("CheckpointReviewId", "VerificationExecutionId")
                        .IsUnique();

                    b.ToTable("checkpoint_review_evidence", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.GitChangedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CheckpointId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IndexStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousPath")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkTreeStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CheckpointId");

                    b.ToTable("git_changed_files", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.GitCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CheckpointNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FingerprintSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadCommitSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "CheckpointNumber")
                        .IsUnique();

                    b.ToTable("git_checkpoints", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.GitWorkspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFailureReasonCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("NextCheckpointNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceBranchName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCommitSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkspaceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkspacePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "WorkspaceNumber")
                        .IsUnique();

                    b.ToTable("git_workspaces", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("NextBaselineNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextExecutionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextVerificationCommandNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int>("NextVerificationExecutionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int>("NextWorkspaceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PhysicalFileId")
                        .HasMaxLength(16)
                        .HasColumnType("BLOB");

                    b.Property<string>("PhysicalIdentityFailureReason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhysicalIdentityStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("PhysicalVolumeSerialNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("RegisteredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationIdentityKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationIdentityKey")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.RepositoryBaseline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BaselineNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadCommitSha")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDirty")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "BaselineNumber")
                        .IsUnique();

                    b.ToTable("repository_baselines", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.RepositoryMutationLease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AcquiredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PhysicalFileId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("BLOB");

                    b.Property<ulong>("PhysicalVolumeSerialNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SupersededAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WorkspaceId")
                        .IsUnique();

                    b.HasIndex("PhysicalVolumeSerialNumber", "PhysicalFileId")
                        .IsUnique()
                        .HasDatabaseName("IX_repository_mutation_leases_physical_identity_active")
                        .HasFilter("\"Status\" = 'Active'");

                    b.ToTable("repository_mutation_leases", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.VerificationCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CommandNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ConfiguredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutablePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CommandNumber")
                        .IsUnique();

                    b.ToTable("verification_commands", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.VerificationExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckpointFingerprintSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ClaimedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletionFingerprintSha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutablePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecutionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GitCheckpointId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GitWorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VerificationCommandId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkspacePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GitCheckpointId");

                    b.HasIndex("VerificationCommandId");

                    b.HasIndex("GitWorkspaceId", "Status");

                    b.HasIndex("ProjectId", "ExecutionNumber")
                        .IsUnique();

                    b.ToTable("verification_executions", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.VerificationOutputArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaptureOutcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativeStoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Truncated")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VerificationExecutionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VerificationExecutionId", "Purpose")
                        .IsUnique();

                    b.ToTable("verification_output_artifacts", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaptureOutcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativeStoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetentionPolicy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sensitivity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Truncated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId", "Purpose")
                        .IsUnique();

                    b.ToTable("artifacts", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.Attempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentAdapterContractVersion")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentCheckpointFingerprintSha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgentContextManifestArtifactId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AgentDispatchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentExpectedMessageType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgentGitCheckpointId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgentGitWorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AgentMaxBytesPerStream")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgentMaxTotalCapturedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentObservedEffort")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentObservedModel")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentOutcome")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentPermissionProfile")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentProtocolVersion")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentProvider")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentProviderSessionId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentRequestedEffort")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentRequestedModel")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentResponseContract")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgentResultGitCheckpointId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentRole")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("AgentTimeout")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ClaimedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Simulated");

                    b.Property<string>("ProcessApprovedRoot")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessArguments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ProcessDispatchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessExecutablePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProcessMaxBytesPerStream")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProcessMaxTotalCapturedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessOutcome")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProcessTimeout")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessWorkingDirectory")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .IsUnique()
                        .HasDatabaseName("ix_attempts_run_id_one_running")
                        .HasFilter("\"Status\" = 'Running'");

                    b.HasIndex("RunId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("attempts", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.AttemptInputMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CollaborationMessageId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId", "CollaborationMessageId")
                        .IsUnique();

                    b.HasIndex("AttemptId", "Sequence")
                        .IsUnique();

                    b.ToTable("attempt_input_messages", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.AttemptVerificationEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VerificationCommandId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VerificationExecutionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VerificationCommandId");

                    b.HasIndex("VerificationExecutionId");

                    b.HasIndex("AttemptId", "Sequence")
                        .IsUnique();

                    b.HasIndex("AttemptId", "VerificationCommandId")
                        .IsUnique();

                    b.HasIndex("AttemptId", "VerificationExecutionId")
                        .IsUnique();

                    b.ToTable("attempt_verification_evidence", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.CollaborationMessage", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActorAgentProvider")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorAgentRole")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InReplyToMessageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtocolVersion")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientAgentProvider")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientAgentRole")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StructuredContentJson")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Sequence");

                    b.HasIndex("AttemptId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("RunId", "InReplyToMessageId");

                    b.HasIndex("RunId", "Sequence")
                        .IsUnique();

                    b.ToTable("collaboration_messages", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.ReviewCorrectionAuthorization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConsumedByAttemptId")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EscalationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HumanInstructionMessageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsumedByAttemptId")
                        .IsUnique()
                        .HasDatabaseName("ix_review_correction_authorizations_attempt_consumed")
                        .HasFilter("\"ConsumedByAttemptId\" IS NOT NULL");

                    b.HasIndex("EscalationId")
                        .IsUnique()
                        .HasDatabaseName("ix_review_correction_authorizations_one_available")
                        .HasFilter("\"ConsumedByAttemptId\" IS NULL");

                    b.HasIndex("HumanInstructionMessageId");

                    b.HasIndex("RunId");

                    b.ToTable("review_correction_authorizations", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.ReviewCorrectionEscalation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CollaborationMessageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ImplementationReviewAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CollaborationMessageId");

                    b.HasIndex("ImplementationReviewAttemptId")
                        .IsUnique();

                    b.HasIndex("RunId");

                    b.ToTable("review_correction_escalations", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AccumulatedAutonomousSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("ActiveAgentProvider")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveAgentRole")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveParticipantKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecutionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastAdvancedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximumReviewCorrectionAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2);

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "ExecutionNumber")
                        .IsUnique();

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.RunEvent", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActorAgentProvider")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorAgentRole")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Sequence");

                    b.HasIndex("AttemptId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("RunId", "Sequence");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.CheckpointReview", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Projects.GitCheckpoint", null)
                        .WithMany()
                        .HasForeignKey("GitCheckpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevalCopilot.Domain.Features.Projects.GitWorkspace", null)
                        .WithMany()
                        .HasForeignKey("GitWorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevalCopilot.Domain.Features.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.CheckpointReviewEvidence", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Projects.CheckpointReview", null)
                        .WithMany("Evidence")
                        .HasForeignKey("CheckpointReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevalCopilot.Domain.Features.Projects.VerificationCommand", null)
                        .WithMany()
                        .HasForeignKey("VerificationCommandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevalCopilot.Domain.Features.Projects.VerificationExecution", null)
                        .WithMany()
                        .HasForeignKey("VerificationExecutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.GitChangedFile", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Projects.GitCheckpoint", null)
                        .WithMany("ChangedFiles")
                        .HasForeignKey("CheckpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.GitCheckpoint", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Projects.GitWorkspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.GitWorkspace", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.RepositoryBaseline", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.RepositoryMutationLease", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevalCopilot.Domain.Features.Projects.GitWorkspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.VerificationCommand", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.VerificationExecution", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Projects.GitCheckpoint", null)
                        .WithMany()
                        .HasForeignKey("GitCheckpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevalCopilot.Domain.Features.Projects.GitWorkspace", null)
                        .WithMany()
                        .HasForeignKey("GitWorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevalCopilot.Domain.Features.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevalCopilot.Domain.Features.Projects.VerificationCommand", null)
                        .WithMany()
                        .HasForeignKey("VerificationCommandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.VerificationOutputArtifact", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Projects.VerificationExecution", null)
                        .WithMany()
                        .HasForeignKey("VerificationExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.Artifact", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Runs.Attempt", null)
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.Attempt", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Runs.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.AttemptInputMessage", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Runs.Attempt", null)
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.AttemptVerificationEvidence", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Runs.Attempt", null)
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevalCopilot.Domain.Features.Projects.VerificationCommand", null)
                        .WithMany()
                        .HasForeignKey("VerificationCommandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevalCopilot.Domain.Features.Projects.VerificationExecution", null)
                        .WithMany()
                        .HasForeignKey("VerificationExecutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.CollaborationMessage", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Runs.Attempt", null)
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DevalCopilot.Domain.Features.Runs.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.ReviewCorrectionAuthorization", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Runs.ReviewCorrectionEscalation", null)
                        .WithMany()
                        .HasForeignKey("EscalationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevalCopilot.Domain.Features.Runs.CollaborationMessage", null)
                        .WithMany()
                        .HasForeignKey("HumanInstructionMessageId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevalCopilot.Domain.Features.Runs.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.ReviewCorrectionEscalation", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Runs.CollaborationMessage", null)
                        .WithMany()
                        .HasForeignKey("CollaborationMessageId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevalCopilot.Domain.Features.Runs.Attempt", null)
                        .WithMany()
                        .HasForeignKey("ImplementationReviewAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevalCopilot.Domain.Features.Runs.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.Run", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.RunEvent", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Runs.Attempt", null)
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DevalCopilot.Domain.Features.Runs.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.CheckpointReview", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.GitCheckpoint", b =>
                {
                    b.Navigation("ChangedFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
