// <auto-generated />
using System;
using DevalCopilot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevalCopilot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DevalCopilotDbContext))]
    [Migration("20260913152558_AddProcessDispatchMarker")]
    partial class AddProcessDispatchMarker
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("NextExecutionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalPath")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.Attempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ClaimedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Simulated");

                    b.Property<string>("ProcessApprovedRoot")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessArguments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ProcessDispatchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessExecutablePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProcessMaxBytesPerStream")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProcessMaxTotalCapturedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessOutcome")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProcessTimeout")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessWorkingDirectory")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("attempts", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AccumulatedAutonomousSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("ActiveParticipant")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecutionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastAdvancedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "ExecutionNumber")
                        .IsUnique();

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.RunEvent", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Sequence");

                    b.HasIndex("AttemptId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("RunId", "Sequence");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.Attempt", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Runs.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.Run", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.RunEvent", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Runs.Attempt", null)
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DevalCopilot.Domain.Features.Runs.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
