// <auto-generated />
using System;
using DevalCopilot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevalCopilot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DevalCopilotDbContext))]
    partial class DevalCopilotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("DevalCopilot.Domain.Features.EnvironmentReadiness.HostCapabilitySnapshot", b =>
                {
                    b.Property<string>("Capability")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EvidenceObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("NextProbeDueAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservedVersion")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ProbeDispatchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedExecutablePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Capability");

                    b.ToTable("host_capability_snapshots", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.GitWorkspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFailureReasonCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceBranchName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCommitSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkspaceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkspacePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "WorkspaceNumber")
                        .IsUnique();

                    b.ToTable("git_workspaces", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("NextBaselineNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextExecutionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextWorkspaceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PhysicalFileId")
                        .HasMaxLength(16)
                        .HasColumnType("BLOB");

                    b.Property<string>("PhysicalIdentityFailureReason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhysicalIdentityStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("PhysicalVolumeSerialNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("RegisteredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationIdentityKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationIdentityKey")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.RepositoryBaseline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BaselineNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadCommitSha")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDirty")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "BaselineNumber")
                        .IsUnique();

                    b.ToTable("repository_baselines", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.RepositoryMutationLease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AcquiredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PhysicalFileId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("BLOB");

                    b.Property<ulong>("PhysicalVolumeSerialNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SupersededAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WorkspaceId")
                        .IsUnique();

                    b.HasIndex("PhysicalVolumeSerialNumber", "PhysicalFileId")
                        .IsUnique()
                        .HasDatabaseName("IX_repository_mutation_leases_physical_identity_active")
                        .HasFilter("\"Status\" = 'Active'");

                    b.ToTable("repository_mutation_leases", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaptureOutcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativeStoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetentionPolicy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sensitivity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Truncated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId", "Purpose")
                        .IsUnique();

                    b.ToTable("artifacts", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.Attempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ClaimedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Simulated");

                    b.Property<string>("ProcessApprovedRoot")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessArguments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ProcessDispatchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessExecutablePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProcessMaxBytesPerStream")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProcessMaxTotalCapturedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessOutcome")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProcessTimeout")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessWorkingDirectory")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("attempts", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AccumulatedAutonomousSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("ActiveParticipant")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecutionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastAdvancedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "ExecutionNumber")
                        .IsUnique();

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.RunEvent", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Sequence");

                    b.HasIndex("AttemptId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("RunId", "Sequence");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.GitWorkspace", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.RepositoryBaseline", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Projects.RepositoryMutationLease", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevalCopilot.Domain.Features.Projects.GitWorkspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.Artifact", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Runs.Attempt", null)
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.Attempt", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Runs.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.Run", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DevalCopilot.Domain.Features.Runs.RunEvent", b =>
                {
                    b.HasOne("DevalCopilot.Domain.Features.Runs.Attempt", null)
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DevalCopilot.Domain.Features.Runs.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
