using System.Text.Json;
using DevalCopilot.Application.Features.Processes.Ports;
using DevalCopilot.Application.Features.Runs.Commands.RecordAgentAttemptResult;
using DevalCopilot.Application.Features.Runs.Policies;
using DevalCopilot.Application.Features.Runs.Ports;
using DevalCopilot.Domain.Features.Projects;
using DevalCopilot.Domain.Features.Runs;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace DevalCopilot.Application.Tests.Features.Runs;

public sealed class RecordAgentAttemptResultCommandHandlerTests(SqliteDatabaseFixture fixture)
    : IClassFixture<SqliteDatabaseFixture>
{
    private static readonly DateTimeOffset Now = new(2026, 9, 17, 12, 0, 0, TimeSpan.Zero);
    private static readonly string Fingerprint = new('a', 64);
    private static readonly IReadOnlyList<SealedAgentArtifact> NoArtifacts = [];

    private static readonly string ValidStructuredContentJson = JsonSerializer.Serialize(new
    {
        scope = "Ledger",
        implementationSteps = "Add the table then the query",
        risks = "Unbounded content",
        verificationPlan = "Tests",
        escalationPoints = "None expected",
    });

    private static (Project Project, Run Run, Attempt Attempt) CreateClaimedAgentAttempt(string? checkpointFingerprint = null)
    {
        var project = Project.Register(Guid.NewGuid(), "DevalCopilot", $@"C:\repos\{Guid.NewGuid():N}", Now);
        var run = Run.RecordIntent(Guid.NewGuid(), project.Id, 1, "Plan the next increment", Now);
        run.Claim(Now);
        var attempt = Attempt.ClaimAgent(
            Guid.NewGuid(), run.Id, 1, Guid.NewGuid(), Guid.NewGuid(), checkpointFingerprint ?? Fingerprint, Guid.NewGuid(),
            TimeSpan.FromMinutes(10), 262144, 524288, Now, 1);
        return (project, run, attempt);
    }

    [Fact]
    public async Task HandleAsync_records_a_valid_proposal_and_maps_it_to_a_collaboration_message()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var proposal = new ValidatedProposal("Add the ledger table and its query.", ValidStructuredContentJson);
        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now.AddMinutes(1)));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(run.Id, attempt.Id, AgentOutcome.Proposed, Fingerprint, NoArtifacts, proposal, null, ProcessEvidence: TestProcessEvidence.ReportedCleanExit),
            CancellationToken.None);

        Assert.True(result.IsSuccess);
        Assert.Equal(AttemptStatus.Completed, result.Value.Status);
        Assert.Equal(AttemptStatus.Completed, attempt.Status);
        Assert.Equal(AgentOutcome.Proposed, attempt.AgentOutcome);

        var message = Assert.Single(dbContext.CollaborationMessages.Where(m => m.RunId == run.Id));
        Assert.Equal(attempt.Id, message.AttemptId);
        Assert.Equal(ParticipantIdentity.ForAgent(AgentRole.Planner, AgentProvider.Codex), message.Actor);
        Assert.Equal(ParticipantIdentity.ForAgentWithUnknownRole(AgentProvider.ClaudeCode), message.Recipient);
        Assert.Equal(CollaborationMessageType.Proposal, message.Type);
        Assert.Equal(CollaborationMessage.ProtocolVersionOne, message.ProtocolVersion);
        Assert.Equal(CollaborationMessageProvenance.ProviderObserved, message.Provenance);
        Assert.Equal(proposal.Summary, message.Summary);
        Assert.Equal(proposal.StructuredContentJson, message.StructuredContentJson);
        Assert.Equal(Now.AddMinutes(1), message.OccurredAtUtc);
        Assert.Null(message.InReplyToMessageId);
        // Host-supplied identity: the message id is generated by the handler itself — the
        // command/ValidatedProposal shape carries no provider-supplied identity field at all.
        Assert.NotEqual(Guid.Empty, message.Id);

        var journalEvent = Assert.Single(dbContext.Events.Where(e => e.AttemptId == attempt.Id));
        Assert.Equal(RunEventType.CollaborationMessageRecorded, journalEvent.EventType);
        Assert.Equal(result.Value.LatestEventSequence, journalEvent.Sequence);
        Assert.Contains(message.Id.ToString(), journalEvent.PayloadJson);
        // Message and event provenance can never diverge: both are the same derived value, never
        // a separately hardcoded literal or a second provider mapping.
        Assert.Equal(message.Actor, journalEvent.Actor);
        Assert.Equal(ParticipantIdentity.ForAgent(AgentRole.Planner, attempt.AgentProvider!.Value), message.Actor);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public async Task HandleAsync_does_not_record_a_provider_session_id_when_absent_or_blank(string? providerSessionId)
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var proposal = new ValidatedProposal("Summary.", ValidStructuredContentJson);
        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(run.Id, attempt.Id, AgentOutcome.Proposed, Fingerprint, NoArtifacts, proposal, providerSessionId, ProcessEvidence: TestProcessEvidence.ReportedCleanExit),
            CancellationToken.None);

        Assert.True(result.IsSuccess);
        Assert.Null(attempt.AgentProviderSessionId);
    }

    [Fact]
    public async Task HandleAsync_records_the_provider_session_id_when_present()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var proposal = new ValidatedProposal("Summary.", ValidStructuredContentJson);
        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(run.Id, attempt.Id, AgentOutcome.Proposed, Fingerprint, NoArtifacts, proposal, "session-abc", ProcessEvidence: TestProcessEvidence.ReportedCleanExit),
            CancellationToken.None);

        Assert.True(result.IsSuccess);
        Assert.Equal("session-abc", attempt.AgentProviderSessionId);
    }

    [Fact]
    public async Task HandleAsync_records_a_provider_invocation_failure_without_appending_a_collaboration_message()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now.AddMinutes(1)));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(run.Id, attempt.Id, AgentOutcome.ProviderInvocationFailed, null, NoArtifacts, null, null),
            CancellationToken.None);

        Assert.True(result.IsSuccess);
        Assert.Equal(AttemptStatus.Failed, attempt.Status);
        Assert.Equal(AgentOutcome.ProviderInvocationFailed, attempt.AgentOutcome);
        Assert.Empty(dbContext.CollaborationMessages.Where(m => m.RunId == run.Id));

        var journalEvent = Assert.Single(dbContext.Events.Where(e => e.AttemptId == attempt.Id));
        Assert.Equal(RunEventType.AgentAttemptCompleted, journalEvent.EventType);
        Assert.Contains("ProviderInvocationFailed", journalEvent.PayloadJson);
    }

    /// <summary>
    /// <see cref="AgentOutcome.SourceChanged"/> is derived exclusively from a fingerprint mismatch
    /// detected by <see cref="Attempt.CompleteAgent"/>'s own override, or by the dedicated
    /// pre-dispatch <c>RecordAgentAttemptSourceChangedCommand</c> — never a caller-selectable
    /// outcome reported directly to this handler. Zero mutation: the attempt, its artifacts, and
    /// the ledger are left completely untouched by a rejected call.
    /// </summary>
    /// <summary>
    /// The closed caller-selectable policy for a Codex planning attempt: <see cref="AgentOutcome.SourceChanged"/>
    /// and <see cref="AgentOutcome.WorkspaceNoLongerEligible"/> belong exclusively to their own
    /// dedicated pre-dispatch commands; <see cref="AgentOutcome.InputAlreadyReviewed"/> belongs
    /// exclusively to its own dedicated command; and <see cref="AgentOutcome.Accepted"/>/
    /// <see cref="AgentOutcome.Challenged"/> belong exclusively to the Claude critical-review
    /// contract. Every one of them must be rejected with a safe, stable error and zero mutation —
    /// never allowed to reach <c>Attempt.CompleteAgent</c>, whose own contract check would
    /// otherwise be the only thing standing between a cross-contract outcome and an unhandled
    /// exception escaping this handler.
    /// </summary>
    [Theory]
    [InlineData(AgentOutcome.SourceChanged)]
    [InlineData(AgentOutcome.WorkspaceNoLongerEligible)]
    [InlineData(AgentOutcome.InputAlreadyReviewed)]
    [InlineData(AgentOutcome.Accepted)]
    [InlineData(AgentOutcome.Challenged)]
    public async Task HandleAsync_rejects_every_non_caller_selectable_outcome_without_mutating_the_attempt(AgentOutcome outcome)
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now.AddMinutes(1)));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(run.Id, attempt.Id, outcome, Fingerprint, NoArtifacts, null, null),
            CancellationToken.None);

        Assert.True(result.IsFailure);
        Assert.Equal("agent_attempts.outcome_not_caller_selectable", Assert.Single(result.Errors).Code);
        Assert.Equal(AttemptStatus.Running, attempt.Status);
        Assert.Null(attempt.AgentOutcome);
        Assert.Empty(dbContext.CollaborationMessages.Where(m => m.RunId == run.Id));
        Assert.Empty(dbContext.Events.Where(e => e.AttemptId == attempt.Id));
        Assert.Empty(dbContext.Artifacts.Where(a => a.AttemptId == attempt.Id));
    }

    [Fact]
    public async Task HandleAsync_rejects_an_undefined_outcome_without_mutating_the_attempt()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now.AddMinutes(1)));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(run.Id, attempt.Id, (AgentOutcome)999, Fingerprint, NoArtifacts, null, null),
            CancellationToken.None);

        Assert.True(result.IsFailure);
        Assert.Equal("agent_attempts.invalid_outcome", Assert.Single(result.Errors).Code);
        Assert.Equal(AttemptStatus.Running, attempt.Status);
        Assert.Null(attempt.AgentOutcome);
        Assert.Empty(dbContext.CollaborationMessages.Where(m => m.RunId == run.Id));
        Assert.Empty(dbContext.Events.Where(e => e.AttemptId == attempt.Id));
        Assert.Empty(dbContext.Artifacts.Where(a => a.AttemptId == attempt.Id));
    }

    [Fact]
    public async Task HandleAsync_overrides_to_source_changed_and_appends_no_proposal_when_fresh_evidence_no_longer_matches_the_claimed_checkpoint()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt(checkpointFingerprint: Fingerprint);
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        // The caller believes it observed a valid Proposal, but the fresh post-invocation Git
        // evidence fingerprint no longer matches what this attempt claimed — the same
        // Attempt.CompleteAgent override rule AttemptTests already exercises directly, now
        // surfaced through this handler.
        var proposal = new ValidatedProposal("Should never be recorded.", ValidStructuredContentJson);
        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now.AddMinutes(1)));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(
                run.Id, attempt.Id, AgentOutcome.Proposed, new string('b', 64), NoArtifacts, proposal, null, ProcessEvidence: TestProcessEvidence.ReportedCleanExit),
            CancellationToken.None);

        Assert.True(result.IsSuccess);
        Assert.Equal(AttemptStatus.Failed, result.Value.Status);
        Assert.Equal(AttemptStatus.Failed, attempt.Status);
        Assert.Equal(AgentOutcome.SourceChanged, attempt.AgentOutcome);
        Assert.Empty(dbContext.CollaborationMessages.Where(m => m.RunId == run.Id));

        var journalEvent = Assert.Single(dbContext.Events.Where(e => e.AttemptId == attempt.Id));
        Assert.Equal(RunEventType.AgentAttemptCompleted, journalEvent.EventType);
        Assert.Contains("SourceChanged", journalEvent.PayloadJson);
    }

    [Fact]
    public async Task HandleAsync_records_sealed_artifacts_with_the_correct_media_type_per_purpose()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var sealedArtifacts = new SealedAgentArtifact[]
        {
            new(ArtifactPurpose.AgentStandardOutput, @"runs\r\attempts\a\stdout.sealed", 12, "sha256:abc", false),
            new(ArtifactPurpose.AgentStandardError, @"runs\r\attempts\a\stderr.sealed", 0, "sha256:def", true),
            new(ArtifactPurpose.AgentFinalResponse, @"runs\r\attempts\a\final.sealed", 34, "sha256:ghi", false),
        };

        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(
                run.Id, attempt.Id, AgentOutcome.ProviderInvocationFailed, null, sealedArtifacts, null, null),
            CancellationToken.None);

        Assert.True(result.IsSuccess);

        var persisted = dbContext.Artifacts.Where(a => a.AttemptId == attempt.Id).ToList();
        Assert.Equal(3, persisted.Count);
        Assert.All(persisted, a => Assert.Equal(ArtifactCaptureOutcome.Captured, a.CaptureOutcome));
        Assert.All(persisted, a => Assert.Equal(ArtifactSensitivity.RedactedBestEffort, a.Sensitivity));
        Assert.All(persisted, a => Assert.Equal(ArtifactRetentionPolicy.RetainUntilRunDeleted, a.RetentionPolicy));

        Assert.Equal("text/plain; charset=utf-8", persisted.Single(a => a.Purpose == ArtifactPurpose.AgentStandardOutput).MediaType);
        Assert.Equal("text/plain; charset=utf-8", persisted.Single(a => a.Purpose == ArtifactPurpose.AgentStandardError).MediaType);
        Assert.Equal("application/json", persisted.Single(a => a.Purpose == ArtifactPurpose.AgentFinalResponse).MediaType);
        Assert.True(persisted.Single(a => a.Purpose == ArtifactPurpose.AgentStandardError).Truncated);
        Assert.False(persisted.Single(a => a.Purpose == ArtifactPurpose.AgentStandardOutput).Truncated);
    }

    [Fact]
    public async Task HandleAsync_fails_when_the_run_does_not_exist()
    {
        await using var dbContext = fixture.CreateContext();

        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(
                Guid.NewGuid(), Guid.NewGuid(), AgentOutcome.ProviderInvocationFailed, null, NoArtifacts, null, null),
            CancellationToken.None);

        Assert.True(result.IsFailure);
        Assert.Equal("runs.not_found", Assert.Single(result.Errors).Code);
    }

    [Fact]
    public async Task HandleAsync_fails_when_the_attempt_does_not_exist()
    {
        await using var dbContext = fixture.CreateContext();
        var project = Project.Register(Guid.NewGuid(), "DevalCopilot", $@"C:\repos\{Guid.NewGuid():N}", Now);
        var run = Run.RecordIntent(Guid.NewGuid(), project.Id, 1, "No attempt yet", Now);
        run.Claim(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(
                run.Id, Guid.NewGuid(), AgentOutcome.ProviderInvocationFailed, null, NoArtifacts, null, null),
            CancellationToken.None);

        Assert.True(result.IsFailure);
        Assert.Equal("runs.not_found", Assert.Single(result.Errors).Code);
    }

    [Fact]
    public async Task HandleAsync_fails_when_the_attempt_belongs_to_a_different_run()
    {
        await using var dbContext = fixture.CreateContext();
        var (targetProject, targetRun, _) = CreateClaimedAgentAttempt();
        var (otherProject, otherRun, otherAttempt) = CreateClaimedAgentAttempt();
        dbContext.Projects.AddRange(targetProject, otherProject);
        dbContext.Runs.AddRange(targetRun, otherRun);
        dbContext.Attempts.Add(otherAttempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(
                targetRun.Id, otherAttempt.Id, AgentOutcome.ProviderInvocationFailed, null, NoArtifacts, null, null),
            CancellationToken.None);

        Assert.True(result.IsFailure);
        Assert.Equal("runs.not_found", Assert.Single(result.Errors).Code);
        Assert.Equal(AttemptStatus.Running, otherAttempt.Status);
    }

    [Fact]
    public async Task HandleAsync_fails_and_does_not_mutate_a_simulated_attempt()
    {
        await using var dbContext = fixture.CreateContext();
        var project = Project.Register(Guid.NewGuid(), "DevalCopilot", $@"C:\repos\{Guid.NewGuid():N}", Now);
        var run = Run.RecordIntent(Guid.NewGuid(), project.Id, 1, "Simulated run", Now);
        run.Claim(Now);
        var attempt = Attempt.Claim(Guid.NewGuid(), run.Id, 1, Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(run.Id, attempt.Id, AgentOutcome.ProviderInvocationFailed, null, NoArtifacts, null, null),
            CancellationToken.None);

        Assert.True(result.IsFailure);
        Assert.Equal("attempts.not_agent", Assert.Single(result.Errors).Code);
        Assert.Equal(AttemptStatus.Running, attempt.Status);
    }

    [Fact]
    public async Task HandleAsync_fails_and_does_not_mutate_an_already_terminal_attempt()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.CompleteAgent(AgentOutcome.ProviderInvocationFailed, null, Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now.AddMinutes(1)));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(run.Id, attempt.Id, AgentOutcome.Proposed, Fingerprint, NoArtifacts, null, null, ProcessEvidence: TestProcessEvidence.ReportedCleanExit),
            CancellationToken.None);

        Assert.True(result.IsFailure);
        Assert.Equal("attempts.not_active", Assert.Single(result.Errors).Code);
        Assert.Equal(AgentOutcome.ProviderInvocationFailed, attempt.AgentOutcome);
    }

    /// <summary>
    /// <see cref="CodexFinalResponseParser"/> is the only production caller that constructs a
    /// <see cref="ValidatedProposal"/>, and it now enforces the exact same
    /// <c>CollaborationMessageContentPolicy</c> bounds and unsafe-content check that
    /// <see cref="CollaborationMessage.Record"/> applies (see
    /// <c>CodexFinalResponseParserTests.TryParse_fails_closed_for_an_overlong_structured_field</c>
    /// and its sibling tests) — a policy-violating provider response never reaches this handler as
    /// a "Proposed" outcome with a non-null <c>Proposal</c> in production. This handler is no
    /// longer a bare pass-through for that hypothetical either: it independently re-validates
    /// <see cref="ValidatedProposal.StructuredContentJson"/> via
    /// <see cref="CollaborationMessageContentPolicy.Validate"/> and maps any resulting
    /// <see cref="ArgumentException"/> to a fail-closed <c>agent_attempts.invalid_proposal_content</c>
    /// result — never an uncaught exception and never a partial mutation.
    /// </summary>
    [Fact]
    public async Task HandleAsync_rejects_a_proposal_with_invalid_structured_content_without_mutating_the_attempt()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var overlongStructuredContent = JsonSerializer.Serialize(new
        {
            scope = new string('x', 950), // Exceeds CollaborationMessageContentPolicy's 900-character field bound.
            implementationSteps = "Add the table then the query",
            risks = "Unbounded content",
            verificationPlan = "Tests",
            escalationPoints = "None expected",
        });
        var proposal = new ValidatedProposal("Summary.", overlongStructuredContent);

        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now.AddMinutes(1)));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(run.Id, attempt.Id, AgentOutcome.Proposed, Fingerprint, NoArtifacts, proposal, null, ProcessEvidence: TestProcessEvidence.ReportedCleanExit),
            CancellationToken.None);

        Assert.True(result.IsFailure);
        Assert.Equal("agent_attempts.invalid_proposal_content", Assert.Single(result.Errors).Code);
        Assert.Equal(AttemptStatus.Running, attempt.Status);
        Assert.Null(attempt.AgentOutcome);
        Assert.Empty(dbContext.CollaborationMessages.Where(m => m.RunId == run.Id));
        Assert.Empty(dbContext.Events.Where(e => e.AttemptId == attempt.Id));
    }

    [Fact]
    public async Task HandleAsync_rejects_a_proposal_with_an_unsafe_summary_without_mutating_the_attempt()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var proposal = new ValidatedProposal("Uses a hardcoded password for the ledger.", ValidStructuredContentJson);
        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now.AddMinutes(1)));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(run.Id, attempt.Id, AgentOutcome.Proposed, Fingerprint, NoArtifacts, proposal, null, ProcessEvidence: TestProcessEvidence.ReportedCleanExit),
            CancellationToken.None);

        Assert.True(result.IsFailure);
        Assert.Equal("agent_attempts.invalid_proposal_content", Assert.Single(result.Errors).Code);
        Assert.Equal(AttemptStatus.Running, attempt.Status);
        Assert.Null(attempt.AgentOutcome);
        Assert.Empty(dbContext.CollaborationMessages.Where(m => m.RunId == run.Id));
        Assert.Empty(dbContext.Events.Where(e => e.AttemptId == attempt.Id));
    }

    [Fact]
    public async Task HandleAsync_rejects_a_result_for_an_attempt_that_was_never_dispatched()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(run.Id, attempt.Id, AgentOutcome.ProviderInvocationFailed, null, NoArtifacts, null, null),
            CancellationToken.None);

        Assert.True(result.IsFailure);
        Assert.Equal("agent_attempts.not_dispatched", Assert.Single(result.Errors).Code);
        Assert.Equal(AttemptStatus.Running, attempt.Status);
        Assert.Null(attempt.AgentOutcome);
        Assert.Empty(dbContext.CollaborationMessages.Where(m => m.RunId == run.Id));
        Assert.Empty(dbContext.Events.Where(e => e.AttemptId == attempt.Id));
        Assert.Empty(dbContext.Artifacts.Where(a => a.AttemptId == attempt.Id));
    }

    [Fact]
    public async Task HandleAsync_rejects_an_undefined_agent_outcome_without_mutating_the_attempt()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now.AddMinutes(1)));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(run.Id, attempt.Id, (AgentOutcome)9999, null, NoArtifacts, null, null),
            CancellationToken.None);

        Assert.True(result.IsFailure);
        Assert.Equal("agent_attempts.invalid_outcome", Assert.Single(result.Errors).Code);
        Assert.Equal(AttemptStatus.Running, attempt.Status);
        Assert.Null(attempt.AgentOutcome);
        Assert.Empty(dbContext.Events.Where(e => e.AttemptId == attempt.Id));
    }

    [Fact]
    public async Task HandleAsync_rejects_a_proposed_outcome_without_a_completion_fingerprint()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var proposal = new ValidatedProposal("Summary.", ValidStructuredContentJson);
        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now.AddMinutes(1)));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(run.Id, attempt.Id, AgentOutcome.Proposed, null, NoArtifacts, proposal, null, ProcessEvidence: TestProcessEvidence.ReportedCleanExit),
            CancellationToken.None);

        Assert.True(result.IsFailure);
        Assert.Equal("agent_attempts.proposed_requires_completion_fingerprint", Assert.Single(result.Errors).Code);
        Assert.Equal(AttemptStatus.Running, attempt.Status);
        Assert.Null(attempt.AgentOutcome);
        Assert.Empty(dbContext.CollaborationMessages.Where(m => m.RunId == run.Id));
        Assert.Empty(dbContext.Events.Where(e => e.AttemptId == attempt.Id));
    }

    [Fact]
    public async Task HandleAsync_rejects_a_proposed_outcome_without_a_proposal()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now.AddMinutes(1)));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(run.Id, attempt.Id, AgentOutcome.Proposed, Fingerprint, NoArtifacts, null, null, ProcessEvidence: TestProcessEvidence.ReportedCleanExit),
            CancellationToken.None);

        Assert.True(result.IsFailure);
        Assert.Equal("agent_attempts.proposed_requires_proposal", Assert.Single(result.Errors).Code);
        Assert.Equal(AttemptStatus.Running, attempt.Status);
        Assert.Null(attempt.AgentOutcome);
        Assert.Empty(dbContext.CollaborationMessages.Where(m => m.RunId == run.Id));
        Assert.Empty(dbContext.Events.Where(e => e.AttemptId == attempt.Id));
    }

    [Fact]
    public async Task HandleAsync_rejects_a_non_proposed_outcome_that_carries_a_proposal()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var proposal = new ValidatedProposal("Should never be recorded.", ValidStructuredContentJson);
        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now.AddMinutes(1)));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(run.Id, attempt.Id, AgentOutcome.ProviderInvocationFailed, null, NoArtifacts, proposal, null),
            CancellationToken.None);

        Assert.True(result.IsFailure);
        Assert.Equal("agent_attempts.proposal_requires_proposed_outcome", Assert.Single(result.Errors).Code);
        Assert.Equal(AttemptStatus.Running, attempt.Status);
        Assert.Null(attempt.AgentOutcome);
        Assert.Empty(dbContext.CollaborationMessages.Where(m => m.RunId == run.Id));
        Assert.Empty(dbContext.Events.Where(e => e.AttemptId == attempt.Id));
    }

    [Fact]
    public async Task HandleAsync_rejects_an_overlong_provider_session_id()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var overlongSessionId = new string('s', 257);
        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now.AddMinutes(1)));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(
                run.Id, attempt.Id, AgentOutcome.ProviderInvocationFailed, null, NoArtifacts, null, overlongSessionId),
            CancellationToken.None);

        Assert.True(result.IsFailure);
        Assert.Equal("agent_attempts.provider_session_id_too_long", Assert.Single(result.Errors).Code);
        Assert.Equal(AttemptStatus.Running, attempt.Status);
        Assert.Null(attempt.AgentOutcome);
        Assert.Null(attempt.AgentProviderSessionId);
        Assert.Empty(dbContext.Events.Where(e => e.AttemptId == attempt.Id));
    }

    [Fact]
    public async Task HandleAsync_rejects_an_unsupported_artifact_purpose()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var sealedArtifacts = new SealedAgentArtifact[]
        {
            new(ArtifactPurpose.AgentContextManifest, @"runs\r\attempts\a\manifest.sealed", 12, "sha256:abc", false),
        };

        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now.AddMinutes(1)));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(
                run.Id, attempt.Id, AgentOutcome.ProviderInvocationFailed, null, sealedArtifacts, null, null),
            CancellationToken.None);

        Assert.True(result.IsFailure);
        Assert.Equal("agent_attempts.unsupported_artifact_purpose", Assert.Single(result.Errors).Code);
        Assert.Equal(AttemptStatus.Running, attempt.Status);
        Assert.Empty(dbContext.Artifacts.Where(a => a.AttemptId == attempt.Id));
        Assert.Empty(dbContext.Events.Where(e => e.AttemptId == attempt.Id));
    }

    [Fact]
    public async Task HandleAsync_rejects_a_duplicate_artifact_purpose()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var sealedArtifacts = new SealedAgentArtifact[]
        {
            new(ArtifactPurpose.AgentStandardOutput, @"runs\r\attempts\a\stdout-1.sealed", 12, "sha256:abc", false),
            new(ArtifactPurpose.AgentStandardOutput, @"runs\r\attempts\a\stdout-2.sealed", 34, "sha256:def", false),
        };

        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now.AddMinutes(1)));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(
                run.Id, attempt.Id, AgentOutcome.ProviderInvocationFailed, null, sealedArtifacts, null, null),
            CancellationToken.None);

        Assert.True(result.IsFailure);
        Assert.Equal("agent_attempts.duplicate_artifact_purpose", Assert.Single(result.Errors).Code);
        Assert.Equal(AttemptStatus.Running, attempt.Status);
        Assert.Empty(dbContext.Artifacts.Where(a => a.AttemptId == attempt.Id));
        Assert.Empty(dbContext.Events.Where(e => e.AttemptId == attempt.Id));
    }

    [Theory]
    [InlineData("", "sha256:abc", 12)]
    [InlineData("   ", "sha256:abc", 12)]
    [InlineData(@"runs\r\attempts\a\stdout.sealed", "", 12)]
    [InlineData(@"runs\r\attempts\a\stdout.sealed", "   ", 12)]
    [InlineData(@"runs\r\attempts\a\stdout.sealed", "sha256:abc", -1)]
    public async Task HandleAsync_rejects_malformed_artifact_metadata(string relativeStoragePath, string contentHash, long byteLength)
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var sealedArtifacts = new SealedAgentArtifact[]
        {
            new(ArtifactPurpose.AgentStandardOutput, relativeStoragePath, byteLength, contentHash, false),
        };

        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now.AddMinutes(1)));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(
                run.Id, attempt.Id, AgentOutcome.ProviderInvocationFailed, null, sealedArtifacts, null, null),
            CancellationToken.None);

        Assert.True(result.IsFailure);
        Assert.Equal("agent_attempts.invalid_artifact_metadata", Assert.Single(result.Errors).Code);
        Assert.Equal(AttemptStatus.Running, attempt.Status);
        Assert.Empty(dbContext.Artifacts.Where(a => a.AttemptId == attempt.Id));
        Assert.Empty(dbContext.Events.Where(e => e.AttemptId == attempt.Id));
    }

    [Fact]
    public async Task HandleAsync_rejects_a_proposal_without_clean_exit_evidence_with_zero_mutation()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var proposal = new ValidatedProposal("Add the ledger table and its query.", ValidStructuredContentJson);
        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now.AddMinutes(1)));
        var missing = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(run.Id, attempt.Id, AgentOutcome.Proposed, Fingerprint, NoArtifacts, proposal, null),
            CancellationToken.None);
        var nonZero = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(
                run.Id, attempt.Id, AgentOutcome.Proposed, Fingerprint, NoArtifacts, proposal, null,
                new AgentProcessEvidence(ProcessExecutionOutcome.Exited, 1, TimeSpan.FromSeconds(3))),
            CancellationToken.None);

        Assert.Equal(AgentProcessEvidenceRecording.CleanExitRequiredCode, Assert.Single(missing.Errors).Code);
        Assert.Equal(AgentProcessEvidenceRecording.CleanExitRequiredCode, Assert.Single(nonZero.Errors).Code);
        await using var verification = fixture.CreateContext();
        var persisted = await verification.Attempts.AsNoTracking().SingleAsync(candidate => candidate.Id == attempt.Id);
        Assert.Equal(AttemptStatus.Running, persisted.Status);
        Assert.Null(persisted.AgentOutcome);
        Assert.Null(persisted.AgentProcessOutcome);
        Assert.Empty(verification.CollaborationMessages.Where(message => message.RunId == run.Id));
    }

    [Fact]
    public async Task HandleAsync_persists_non_zero_exit_evidence_atomically_with_the_provider_failure()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now.AddMinutes(1)));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(
                run.Id, attempt.Id, AgentOutcome.ProviderInvocationFailed, null, NoArtifacts, null, null,
                new AgentProcessEvidence(ProcessExecutionOutcome.Exited, 2, TimeSpan.FromMilliseconds(987))),
            CancellationToken.None);

        Assert.True(result.IsSuccess);
        await using var verification = fixture.CreateContext();
        var persisted = await verification.Attempts.AsNoTracking().SingleAsync(candidate => candidate.Id == attempt.Id);
        Assert.Equal(AttemptStatus.Failed, persisted.Status);
        Assert.Equal(AgentOutcome.ProviderInvocationFailed, persisted.AgentOutcome);
        Assert.Equal(Now.AddMinutes(1), persisted.CompletedAtUtc);
        Assert.Equal(ProcessOutcome.Exited, persisted.AgentProcessOutcome);
        Assert.Equal(2, persisted.AgentProcessExitCode);
        Assert.Equal(TimeSpan.FromMilliseconds(987), persisted.AgentProcessDuration);
    }

    [Fact]
    public async Task HandleAsync_rejects_malformed_evidence_with_zero_mutation()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now.AddMinutes(1)));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(
                run.Id, attempt.Id, AgentOutcome.ProviderInvocationFailed, null, NoArtifacts, null, null,
                new AgentProcessEvidence(ProcessExecutionOutcome.TimedOut, 124, TimeSpan.FromSeconds(1))),
            CancellationToken.None);

        Assert.Equal(AgentProcessEvidenceRecording.InvalidEvidenceCode, Assert.Single(result.Errors).Code);
        Assert.Equal(AttemptStatus.Running, attempt.Status);
        Assert.Null(attempt.AgentProcessOutcome);
    }

    [Fact]
    public async Task HandleAsync_rejects_claude_usage_on_a_codex_proposal_with_zero_mutation()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var proposal = new ValidatedProposal("Add the ledger table and its query.", ValidStructuredContentJson);
        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now.AddMinutes(1)));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(
                run.Id, attempt.Id, AgentOutcome.Proposed, Fingerprint, NoArtifacts, proposal, null,
                TestProcessEvidence.ReportedCleanExit, TestTokenUsage.Reported),
            CancellationToken.None);

        Assert.Equal(AgentTokenUsageRecording.InvalidEvidenceCode, Assert.Single(result.Errors).Code);
        await using var verification = fixture.CreateContext();
        var persisted = await verification.Attempts.AsNoTracking().SingleAsync(candidate => candidate.Id == attempt.Id);
        Assert.Equal(AttemptStatus.Running, persisted.Status);
        Assert.Null(persisted.AgentOutcome);
        Assert.Null(persisted.GetAgentProcessExecutionEvidence());
        Assert.Null(persisted.GetAgentTokenUsageEvidence());
        Assert.Empty(verification.CollaborationMessages.Where(message => message.RunId == run.Id));
    }

    [Fact]
    public async Task HandleAsync_rejects_claude_usage_on_a_codex_provider_failure_with_zero_mutation()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now.AddMinutes(1)));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(
                run.Id, attempt.Id, AgentOutcome.ProviderInvocationFailed, null, NoArtifacts, null, null,
                new AgentProcessEvidence(ProcessExecutionOutcome.Exited, 1, TimeSpan.FromSeconds(2)), TestTokenUsage.Reported),
            CancellationToken.None);

        Assert.Equal(AgentTokenUsageRecording.InvalidEvidenceCode, Assert.Single(result.Errors).Code);
        await using var verification = fixture.CreateContext();
        var persisted = await verification.Attempts.AsNoTracking().SingleAsync(candidate => candidate.Id == attempt.Id);
        Assert.Equal(AttemptStatus.Running, persisted.Status);
        Assert.Null(persisted.AgentProcessExitCode);
        Assert.Null(persisted.GetAgentTokenUsageEvidence());
    }

    [Fact]
    public async Task HandleAsync_records_codex_usage_reported_through_its_own_proven_schema()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var proposal = new ValidatedProposal("Add the ledger table and its query.", ValidStructuredContentJson);
        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now.AddMinutes(1)));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(
                run.Id, attempt.Id, AgentOutcome.Proposed, Fingerprint, NoArtifacts, proposal, null,
                TestProcessEvidence.ReportedCleanExit, TestTokenUsage.CodexReported),
            CancellationToken.None);

        Assert.True(result.IsSuccess);
        await using var verification = fixture.CreateContext();
        var persisted = await verification.Attempts.AsNoTracking().SingleAsync(candidate => candidate.Id == attempt.Id);
        Assert.Equal(AttemptStatus.Completed, persisted.Status);
        Assert.Equal(2400, persisted.AgentInputTokens);
        Assert.Equal(120, persisted.AgentOutputTokens);
        Assert.Null(persisted.AgentCacheCreationInputTokens);
        Assert.Null(persisted.AgentCacheReadInputTokens);
        Assert.Equal("codex-cli-usage-v1", persisted.AgentTokenUsageSchemaVersion);
        Assert.Equal(TestTokenUsage.CodexEvidence, persisted.GetAgentTokenUsageEvidence());
    }

    [Fact]
    public async Task HandleAsync_records_no_token_usage_when_none_was_reported()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var proposal = new ValidatedProposal("Add the ledger table and its query.", ValidStructuredContentJson);
        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now.AddMinutes(1)));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(
                run.Id, attempt.Id, AgentOutcome.Proposed, Fingerprint, NoArtifacts, proposal, null, TestProcessEvidence.ReportedCleanExit),
            CancellationToken.None);

        Assert.True(result.IsSuccess);
        await using var verification = fixture.CreateContext();
        var persisted = await verification.Attempts.AsNoTracking().SingleAsync(candidate => candidate.Id == attempt.Id);
        Assert.Equal(AttemptStatus.Completed, persisted.Status);
        Assert.Null(persisted.AgentInputTokens);
        Assert.Null(persisted.AgentTokenUsageSchemaVersion);
        Assert.Null(persisted.GetAgentTokenUsageEvidence());
    }

    [Fact]
    public async Task HandleAsync_rejects_malformed_token_usage_with_zero_mutation()
    {
        await using var dbContext = fixture.CreateContext();
        var (project, run, attempt) = CreateClaimedAgentAttempt();
        attempt.MarkAgentDispatched(Now);
        dbContext.Projects.Add(project);
        dbContext.Runs.Add(run);
        dbContext.Attempts.Add(attempt);
        await dbContext.SaveChangesAsync(CancellationToken.None);

        var proposal = new ValidatedProposal("Add the ledger table and its query.", ValidStructuredContentJson);
        var handler = new RecordAgentAttemptResultCommandHandler(dbContext, new FixedTimeProvider(Now.AddMinutes(1)));
        var result = await handler.HandleAsync(
            new RecordAgentAttemptResultCommand(
                run.Id, attempt.Id, AgentOutcome.Proposed, Fingerprint, NoArtifacts, proposal, null,
                TestProcessEvidence.ReportedCleanExit, new AgentTokenUsage(-1, 5, 0, 0, "claude-cli-usage-v1")),
            CancellationToken.None);

        Assert.Equal(AgentTokenUsageRecording.InvalidEvidenceCode, Assert.Single(result.Errors).Code);
        await using var verification = fixture.CreateContext();
        var persisted = await verification.Attempts.AsNoTracking().SingleAsync(candidate => candidate.Id == attempt.Id);
        Assert.Equal(AttemptStatus.Running, persisted.Status);
        Assert.Null(persisted.AgentOutcome);
        Assert.Null(persisted.AgentProcessOutcome);
        Assert.Null(persisted.AgentInputTokens);
        Assert.Empty(verification.CollaborationMessages.Where(message => message.RunId == run.Id));
    }
}
