namespace DevalCopilot.Application.Features.Projects.Commands.ConfigureVerificationCommand;

public sealed record ConfigureVerificationCommandCommandResult(Guid VerificationCommandId, int CommandNumber);
